import type { Collaborator, Project } from './types'

/** Datos de demo. En producción vendrían de Supabase. */

export const seedCollaborators: Collaborator[] = [
  {
    id: 'c1',
    name: 'Ramón Ortega',
    specialty: 'Full-stack · React + Postgres',
    role: 'owner',
    avatarHue: 265,
    projectIds: ['p1', 'p2', 'p3'],
  },
  {
    id: 'c2',
    name: 'Lucía Ferrer',
    specialty: 'Diseño de producto · Design systems',
    role: 'maintainer',
    avatarHue: 155,
    projectIds: ['p1', 'p3'],
  },
  {
    id: 'c3',
    name: 'Diego Salas',
    specialty: 'Data engineering · Pipelines ETL',
    role: 'collaborator',
    avatarHue: 290,
    projectIds: ['p2'],
  },
  {
    id: 'c4',
    name: 'Nora Beltrán',
    specialty: 'FinOps · Costo de infraestructura',
    role: 'collaborator',
    avatarHue: 200,
    projectIds: ['p1', 'p2'],
  },
  {
    id: 'c5',
    name: 'Iván Cortés',
    specialty: 'DevOps · CI/CD y observabilidad',
    role: 'maintainer',
    avatarHue: 320,
    projectIds: ['p3'],
  },
]

export const seedProjects: Project[] = [
  {
    id: 'p1',
    name: 'Nébula Checkout',
    description: 'Pasarela de pagos multi-moneda con conciliación automática.',
    hue: 265,
    createdAt: '2026-03-04',
    budget: { allocated: 48000, spent: 29650, currency: 'USD' },
    collaboratorIds: ['c1', 'c2', 'c4'],
    repo: {
      provider: 'github',
      fullName: 'nebula-labs/checkout-core',
      branch: 'main',
      connectedAt: '2026-03-04',
      lastSync: 'hace 2 min',
      stats: { commits: 1284, openPRs: 6, mergedPRs: 212, contributors: 9, coverage: 81 },
    },
    database: {
      provider: 'supabase',
      projectRef: 'zqfhtnbxrlwpaosdvkeg',
      region: 'sa-east-1',
      tables: 24,
      migrations: 63,
      rlsEnabled: true,
    },
    tasks: [
      { id: 't1', title: 'Webhook de reintentos con backoff exponencial', status: 'done', owner: 'Constructor', source: 'agent', ref: 'PR #211', autoSynced: true, points: 5 },
      { id: 't2', title: 'Índices compuestos en tabla transactions', status: 'done', owner: 'Arquitecto', source: 'agent', ref: 'migration 0063', autoSynced: true, points: 3 },
      { id: 't3', title: 'Auditoría de RLS en payment_methods', status: 'review', owner: 'Auditor', source: 'agent', ref: 'PR #214', points: 8 },
      { id: 't4', title: 'Conciliación diaria contra extracto bancario', status: 'progress', owner: 'Constructor', source: 'agent', ref: 'feat/reconcile', points: 13 },
      { id: 't5', title: 'Rediseño del flujo de 3DS', status: 'progress', owner: 'Lucía Ferrer', source: 'human', points: 8 },
      { id: 't6', title: 'Reporte de costo por transacción', status: 'backlog', owner: 'Analista', source: 'agent', points: 5 },
      { id: 't7', title: 'Migrar a Stripe Payment Intents v2', status: 'backlog', owner: 'Arquitecto', source: 'github', ref: 'issue #198', points: 21 },
    ],
  },
  {
    id: 'p2',
    name: 'Atlas Analytics',
    description: 'Warehouse y capa semántica para reportes financieros.',
    hue: 155,
    createdAt: '2026-01-19',
    budget: { allocated: 72000, spent: 61400, currency: 'USD' },
    collaboratorIds: ['c1', 'c3', 'c4'],
    repo: {
      provider: 'github',
      fullName: 'atlas-data/warehouse',
      branch: 'develop',
      connectedAt: '2026-01-19',
      lastSync: 'hace 14 min',
      stats: { commits: 2971, openPRs: 11, mergedPRs: 486, contributors: 14, coverage: 67 },
    },
    database: {
      provider: 'supabase',
      projectRef: 'mklopwzbtscfvdqrhnja',
      region: 'us-east-1',
      tables: 58,
      migrations: 142,
      rlsEnabled: true,
    },
    tasks: [
      { id: 't10', title: 'Modelo dbt para ingresos recurrentes', status: 'done', owner: 'Constructor', source: 'agent', ref: 'PR #480', autoSynced: true, points: 8 },
      { id: 't11', title: 'Alertas de varianza presupuestaria', status: 'review', owner: 'Analista', source: 'agent', ref: 'PR #486', points: 5 },
      { id: 't12', title: 'Particionado de fact_events por mes', status: 'progress', owner: 'Diego Salas', source: 'human', points: 13 },
      { id: 't13', title: 'Documentar linaje de métricas', status: 'progress', owner: 'Cronista', source: 'agent', autoSynced: true, points: 3 },
      { id: 't14', title: 'Reducir costo de queries en dashboards', status: 'backlog', owner: 'Nora Beltrán', source: 'human', points: 8 },
    ],
  },
  {
    id: 'p3',
    name: 'Orion Mobile',
    description: 'App cliente con modo offline y sincronización diferencial.',
    hue: 320,
    createdAt: '2026-05-22',
    budget: { allocated: 35000, spent: 8200, currency: 'USD' },
    collaboratorIds: ['c1', 'c2', 'c5'],
    repo: null,
    database: null,
    tasks: [
      { id: 't20', title: 'Definir contrato de sincronización', status: 'progress', owner: 'Arquitecto', source: 'agent', points: 8 },
      { id: 't21', title: 'Investigar SQLite vs WatermelonDB', status: 'backlog', owner: 'Estratega', source: 'agent', points: 5 },
      { id: 't22', title: 'Sistema de diseño compartido con web', status: 'backlog', owner: 'Lucía Ferrer', source: 'human', points: 13 },
    ],
  },
]
